- product: onemkl
  release: 2024.2.0
  tests:
    https://github.com/intel-innersource/frameworks.devops.ci.tests.mkl:
      timeout: 14400
- product: tensorflow
  release: 2024.2.0
  tests:
    https://github.com/intel-innersource/frameworks.devops.ci.tests.tensorflow:
      timeout: 3600
